[2024-08-05T14:43:52.524+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T14:43:52.607+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_air_pollution_data_dag.clean_data manual__2024-08-05T11:43:42.654312+00:00 [queued]>
[2024-08-05T14:43:52.622+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_air_pollution_data_dag.clean_data manual__2024-08-05T11:43:42.654312+00:00 [queued]>
[2024-08-05T14:43:52.623+0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-05T14:43:52.697+0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): clean_data> on 2024-08-05 11:43:42.654312+00:00
[2024-08-05T14:43:52.713+0300] {standard_task_runner.py:64} INFO - Started process 94351 to run task
[2024-08-05T14:43:52.723+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'process_air_pollution_data_dag', 'clean_data', 'manual__2024-08-05T11:43:42.654312+00:00', '--job-id', '308', '--raw', '--subdir', 'DAGS_FOLDER/process_air_pollution_data_dag.py', '--cfg-path', '/tmp/tmpgf83dydp']
[2024-08-05T14:43:52.724+0300] {standard_task_runner.py:91} INFO - Job 308: Subtask clean_data
[2024-08-05T14:43:52.810+0300] {task_command.py:426} INFO - Running <TaskInstance: process_air_pollution_data_dag.clean_data manual__2024-08-05T11:43:42.654312+00:00 [running]> on host std21092
[2024-08-05T14:43:52.932+0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='process_air_pollution_data_dag' AIRFLOW_CTX_TASK_ID='clean_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-05T11:43:42.654312+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-05T11:43:42.654312+00:00'
[2024-08-05T14:43:52.934+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T14:43:52.935+0300] {logging_mixin.py:188} INFO - Erreur lors du nettoyage des donn√©es : read_csv() got an unexpected keyword argument 'error_bad_lines'
[2024-08-05T14:43:52.935+0300] {python.py:237} INFO - Done. Returned value was: None
[2024-08-05T14:43:52.935+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T14:43:52.940+0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=process_air_pollution_data_dag, task_id=clean_data, run_id=manual__2024-08-05T11:43:42.654312+00:00, execution_date=20240805T114342, start_date=20240805T114352, end_date=20240805T114352
[2024-08-05T14:43:52.981+0300] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-05T14:43:53.004+0300] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-05T14:43:53.029+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
