[2024-08-05T13:48:39.431+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T13:48:39.462+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_pollution_data_dag.fetch_air_pollution_data_Lima manual__2024-08-05T10:42:36.434288+00:00 [queued]>
[2024-08-05T13:48:39.469+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_pollution_data_dag.fetch_air_pollution_data_Lima manual__2024-08-05T10:42:36.434288+00:00 [queued]>
[2024-08-05T13:48:39.469+0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-05T13:48:39.483+0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_air_pollution_data_Lima> on 2024-08-05 10:42:36.434288+00:00
[2024-08-05T13:48:39.487+0300] {standard_task_runner.py:64} INFO - Started process 71717 to run task
[2024-08-05T13:48:39.490+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'air_pollution_data_dag', 'fetch_air_pollution_data_Lima', 'manual__2024-08-05T10:42:36.434288+00:00', '--job-id', '285', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp0b3fzy0e']
[2024-08-05T13:48:39.490+0300] {standard_task_runner.py:91} INFO - Job 285: Subtask fetch_air_pollution_data_Lima
[2024-08-05T13:48:39.523+0300] {task_command.py:426} INFO - Running <TaskInstance: air_pollution_data_dag.fetch_air_pollution_data_Lima manual__2024-08-05T10:42:36.434288+00:00 [running]> on host std21092
[2024-08-05T13:48:39.589+0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='air_pollution_data_dag' AIRFLOW_CTX_TASK_ID='fetch_air_pollution_data_Lima' AIRFLOW_CTX_EXECUTION_DATE='2024-08-05T10:42:36.434288+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-05T10:42:36.434288+00:00'
[2024-08-05T13:48:39.590+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T13:48:42.292+0300] {logging_mixin.py:188} INFO - Erreur lors de la récupération des données pour Lima
[2024-08-05T13:48:42.293+0300] {python.py:237} INFO - Done. Returned value was: None
[2024-08-05T13:48:42.294+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T13:48:42.306+0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=air_pollution_data_dag, task_id=fetch_air_pollution_data_Lima, run_id=manual__2024-08-05T10:42:36.434288+00:00, execution_date=20240805T104236, start_date=20240805T104839, end_date=20240805T104842
[2024-08-05T13:48:42.353+0300] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-05T13:48:42.390+0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-05T13:48:42.391+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
