[2024-08-05T13:56:20.687+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T13:56:20.748+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_pollution_data_dag.clean_data manual__2024-08-05T10:55:18.903534+00:00 [queued]>
[2024-08-05T13:56:20.766+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_pollution_data_dag.clean_data manual__2024-08-05T10:55:18.903534+00:00 [queued]>
[2024-08-05T13:56:20.766+0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-05T13:56:20.841+0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): clean_data> on 2024-08-05 10:55:18.903534+00:00
[2024-08-05T13:56:20.848+0300] {standard_task_runner.py:64} INFO - Started process 74480 to run task
[2024-08-05T13:56:20.853+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'air_pollution_data_dag', 'clean_data', 'manual__2024-08-05T10:55:18.903534+00:00', '--job-id', '292', '--raw', '--subdir', 'DAGS_FOLDER/air_pollution_data_dag.py', '--cfg-path', '/tmp/tmp4h4iwe1t']
[2024-08-05T13:56:20.854+0300] {standard_task_runner.py:91} INFO - Job 292: Subtask clean_data
[2024-08-05T13:56:20.930+0300] {task_command.py:426} INFO - Running <TaskInstance: air_pollution_data_dag.clean_data manual__2024-08-05T10:55:18.903534+00:00 [running]> on host std21092
[2024-08-05T13:56:21.056+0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='air_pollution_data_dag' AIRFLOW_CTX_TASK_ID='clean_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-05T10:55:18.903534+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-05T10:55:18.903534+00:00'
[2024-08-05T13:56:21.057+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T13:56:21.062+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T13:56:21.063+0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/safidy/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/safidy/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/safidy/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/safidy/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/safidy/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/safidy/airflow/dags/air_pollution_data_dag.py", line 46, in clean_data
    df = pd.read_csv(csv_file)
  File "/home/safidy/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/safidy/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 583, in _read
    return parser.read(nrows)
  File "/home/safidy/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1704, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/home/safidy/.local/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 875, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 850, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 861, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "pandas/_libs/parsers.pyx", line 2029, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 3 fields in line 3, saw 10

[2024-08-05T13:56:21.073+0300] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=air_pollution_data_dag, task_id=clean_data, run_id=manual__2024-08-05T10:55:18.903534+00:00, execution_date=20240805T105518, start_date=20240805T105620, end_date=20240805T105621
[2024-08-05T13:56:21.090+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 292 for task clean_data (Error tokenizing data. C error: Expected 3 fields in line 3, saw 10
; 74480)
[2024-08-05T13:56:21.108+0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-05T13:56:21.170+0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-05T13:56:21.171+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
