[2024-08-05T13:55:22.521+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T13:55:22.544+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_pollution_data_dag.fetch_air_pollution_data_Los_Angeles manual__2024-08-05T10:55:18.903534+00:00 [queued]>
[2024-08-05T13:55:22.550+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_pollution_data_dag.fetch_air_pollution_data_Los_Angeles manual__2024-08-05T10:55:18.903534+00:00 [queued]>
[2024-08-05T13:55:22.550+0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-05T13:55:22.564+0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_air_pollution_data_Los_Angeles> on 2024-08-05 10:55:18.903534+00:00
[2024-08-05T13:55:22.568+0300] {standard_task_runner.py:64} INFO - Started process 73845 to run task
[2024-08-05T13:55:22.572+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'air_pollution_data_dag', 'fetch_air_pollution_data_Los_Angeles', 'manual__2024-08-05T10:55:18.903534+00:00', '--job-id', '286', '--raw', '--subdir', 'DAGS_FOLDER/air_pollution_data_dag.py', '--cfg-path', '/tmp/tmpvrkvjgsq']
[2024-08-05T13:55:22.573+0300] {standard_task_runner.py:91} INFO - Job 286: Subtask fetch_air_pollution_data_Los_Angeles
[2024-08-05T13:55:22.617+0300] {task_command.py:426} INFO - Running <TaskInstance: air_pollution_data_dag.fetch_air_pollution_data_Los_Angeles manual__2024-08-05T10:55:18.903534+00:00 [running]> on host std21092
[2024-08-05T13:55:22.705+0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='air_pollution_data_dag' AIRFLOW_CTX_TASK_ID='fetch_air_pollution_data_Los_Angeles' AIRFLOW_CTX_EXECUTION_DATE='2024-08-05T10:55:18.903534+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-05T10:55:18.903534+00:00'
[2024-08-05T13:55:22.706+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T13:55:33.890+0300] {logging_mixin.py:188} INFO - Erreur lors de la récupération des données pour Los_Angeles: 401 - {"cod":401, "message": "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."}
[2024-08-05T13:55:33.891+0300] {python.py:237} INFO - Done. Returned value was: None
[2024-08-05T13:55:33.892+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T13:55:33.907+0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=air_pollution_data_dag, task_id=fetch_air_pollution_data_Los_Angeles, run_id=manual__2024-08-05T10:55:18.903534+00:00, execution_date=20240805T105518, start_date=20240805T105522, end_date=20240805T105533
[2024-08-05T13:55:33.981+0300] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-05T13:55:34.043+0300] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-05T13:55:34.048+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
